// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpUlHxKMPtRThANHAqpZ568yCngvMerY',
    appId: '1:573461178945:web:63342ac778b57ec9b534c0',
    messagingSenderId: '573461178945',
    projectId: 'authacc-ae088',
    authDomain: 'authacc-ae088.firebaseapp.com',
    storageBucket: 'authacc-ae088.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmSPuDbRH-N6gHQeImQvDsHQUexzsPtdY',
    appId: '1:573461178945:android:edad74642d7603cbb534c0',
    messagingSenderId: '573461178945',
    projectId: 'authacc-ae088',
    storageBucket: 'authacc-ae088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDsovdZOFLyfA2kl_MbPMLQL2Xta-tXI',
    appId: '1:573461178945:ios:3cd5e9d15513cc1fb534c0',
    messagingSenderId: '573461178945',
    projectId: 'authacc-ae088',
    storageBucket: 'authacc-ae088.appspot.com',
    iosClientId: '573461178945-esfvursdob7h5ocun7qgkaacm6tkdse1.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDsovdZOFLyfA2kl_MbPMLQL2Xta-tXI',
    appId: '1:573461178945:ios:3cd5e9d15513cc1fb534c0',
    messagingSenderId: '573461178945',
    projectId: 'authacc-ae088',
    storageBucket: 'authacc-ae088.appspot.com',
    iosClientId: '573461178945-esfvursdob7h5ocun7qgkaacm6tkdse1.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnpUlHxKMPtRThANHAqpZ568yCngvMerY',
    appId: '1:573461178945:web:694c055d92318cf9b534c0',
    messagingSenderId: '573461178945',
    projectId: 'authacc-ae088',
    authDomain: 'authacc-ae088.firebaseapp.com',
    storageBucket: 'authacc-ae088.appspot.com',
  );

}